import type { BlueprintsData } from '../types'

export const SAMPLE: BlueprintsData = {
  blueprints: [
    {
      name: 'Angled Grip II',
      workshop: 'Gunsmith II',
      image: '',
      crafting_recipe: [
        { item: 'Mechanical Components', quantity: 2 },
        { item: 'Duct Tape', quantity: 3 },
      ],
      available: true,
      loot: true,
      harvester_event: false,
      quest_reward: false,
      trials_reward: false,
    },
    {
      name: 'Angled Grip III',
      workshop: 'Gunsmith III',
      image: '',
      crafting_recipe: [
        { item: 'Mod Components', quantity: 2 },
        { item: 'Duct Tape', quantity: 5 },
      ],
      available: true,
      loot: true,
      harvester_event: false,
      quest_reward: false,
      trials_reward: false,
    },
    {
      name: 'Anvil',
      workshop: 'Gunsmith II',
      image: '',
      crafting_recipe: [
        { item: 'Mechanical Components', quantity: 5 },
        { item: 'Simple Gun Parts', quantity: 5 },
      ],
      available: true,
      loot: true,
      harvester_event: false,
      quest_reward: false,
      trials_reward: true,
    },
    {
      name: 'Anvil Splitter',
      workshop: 'N/A',
      image: '',
      crafting_recipe: [{ item: 'N/A', quantity: 0 }],
      available: true,
      loot: false,
      harvester_event: false,
      quest_reward: false,
      trials_reward: false,
    },
    {
      name: 'Aphelion',
      workshop: 'Gunsmith III',
      image: '',
      crafting_recipe: [
        { item: 'Magnetic Accelerator', quantity: 3 },
        { item: 'Complex Gun Parts', quantity: 5 },
        { item: 'Matriarch Reactor', quantity: 1 },
      ],
      available: true,
      loot: true,
      harvester_event: false,
      quest_reward: false,
      trials_reward: false,
    },
    {
      name: 'Barricade Kit',
      workshop: 'Utility Station II',
      image: '',
      crafting_recipe: [{ item: 'Mechanical Components', quantity: 1 }],
      available: true,
      loot: true,
      harvester_event: false,
      quest_reward: false,
      trials_reward: false,
    },
    {
      name: 'Bettina',
      workshop: 'Gunsmith III',
      image: '',
      crafting_recipe: [
        { item: 'Advanced Mechanical Components', quantity: 3 },
        { item: 'Heavy Gun Parts', quantity: 3 },
        { item: 'Canister', quantity: 3 },
      ],
      available: true,
      loot: true,
      harvester_event: false,
      quest_reward: false,
      trials_reward: false,
    },
    {
      name: 'Blaze Grenade',
      workshop: 'Explosives Station III',
      image: '',
      crafting_recipe: [
        { item: 'Explosive Compound', quantity: 1 },
        { item: 'Oil', quantity: 2 },
      ],
      available: true,
      loot: true,
      harvester_event: false,
      quest_reward: false,
      trials_reward: true,
    },
    {
      name: 'Blue Light Stick',
      workshop: 'Utility Station I',
      image: '',
      crafting_recipe: [{ item: 'Chemicals', quantity: 3 }],
      available: true,
      loot: true,
      harvester_event: false,
      quest_reward: false,
      trials_reward: true,
    },
    {
      name: 'Bobcat',
      workshop: 'Gunsmith III',
      image: '',
      crafting_recipe: [
        { item: 'Magnetic Accelerator', quantity: 1 },
        { item: 'Light Gun Parts', quantity: 3 },
        { item: 'Exodus Modules', quantity: 2 },
      ],
      available: true,
      loot: true,
      harvester_event: false,
      quest_reward: false,
      trials_reward: false,
    },
  ],
}
